
services:
  logging-service:
    profiles:
      - donotstart
    build:
      context: src/Services/LoggingService/
      dockerfile: src/LoggingService.API/Dockerfile
  engine-service:
    profiles:
      - donotstart
    build:
      context: src/Services/EngineService/
      dockerfile: src/EngineService.API/Dockerfile
  sportsdata-service:
    profiles:
      - donotstart
    build:
      context: src/Services/SportsDataService/
      dockerfile: src/SportsDataService.API/Dockerfile
  simulation-service:
    profiles:
      - donotstart
    build:
      context: src/Services/SimulationService/
      dockerfile: src/SimulationService.API/Dockerfile
  statistics-service:
    profiles:
      - donotstart
    build:
      context: src/Services/StatisticsService/
      dockerfile: src/StatisticsService.API/Dockerfile
  frontend:
    profiles:
      - donotstart
    container_name: simpitchweb
    build:
      context: ./src/Frontend/sim-pitch-web
      dockerfile: Dockerfile.dev

  gateway:
    profiles:
      - donotstart
    container_name: nginx-gateway
    image: nginx:1.25-alpine
  redis-cache:
    profiles:
      - donotstart
    container_name: redis-service
    image: redis:6.2-alpine



  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest

     
  mssql-init:
    image: mcr.microsoft.com/mssql-tools
  seed-data:
    build:
      context: sql/seed-data/
      dockerfile: Dockerfile.seed



networks:
  backend_network:
volumes:
  mssql_data:
  cache_data: