
services:
  simulationapi:
    build:
      context: .
      dockerfile: Services/SimulationAPI/Dockerfile
  sportsdataapi:
    build:
      context: .
      dockerfile: Services/SportsDataAPI/Dockerfile
    

networks:
  backend_network:
