
services:
  logging-service:
    build:
      context: ./Services
      dockerfile: LoggingService/src/LoggingService.API/Dockerfile
  sportsdata-service:
    build:
      context: .
      dockerfile: Services/SportsDataService/src/SportsDataService.API/Dockerfile



  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
  mssql-init:
    image: mcr.microsoft.com/mssql-tools
    
networks:
  backend_network:
volumes:
  mssql_data:
