services:
  simulationapi:
    ports:
      - "${SIMULATIONAPI_HOST_PORT}:${SIMULATIONAPI_CONTAINER_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URL}:${SIMULATIONAPI_CONTAINER_PORT}
    networks:
      - backend_network
  sportsdataapi:
    ports:
      - "${SPORTSDATAAPI_HOST_PORT}:${SPORTSDATAAPI_CONTAINER_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URL}:${SPORTSDATAAPI_CONTAINER_PORT}
    networks:
      - backend_network
